[
    {
        "created_at": "Sat Jun 08 10:00:02 +0000 2013",
        "id": 343306413906481150,
        "id_str": "343306413906481153",
        "text": "Lorem ipsum tweets at coffee time http://t.co/RfAeb8d9dh for web designers and wireframes 11:00 08-06-2013 #tweepsum",
        "source": "<a href=\"http://www.danfast.com\" rel=\"nofollow\">Tweepsum</a>",
        "truncated": false,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "in_reply_to_screen_name": null,
        "user": {
            "id": 242486125,
            "id_str": "242486125",
            "name": "Tweepsum",
            "screen_name": "tweepsum",
            "location": "Poole, Dorset, UK",
            "url": "http://danfast.com/tweepsum",
            "description": "Average & full length lorem ipsum tweets at coffee time each day for web designers or anyone needing a test Twitter feed",
            "protected": false,
            "followers_count": 59,
            "friends_count": 0,
            "listed_count": 0,
            "created_at": "Mon Jan 24 22:12:50 +0000 2011",
            "favourites_count": 0,
            "utc_offset": 0,
            "time_zone": "London",
            "geo_enabled": false,
            "verified": false,
            "statuses_count": 409,
            "lang": "en",
            "contributors_enabled": false,
            "is_translator": false,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_tile": false,
            "profile_image_url": "http://a0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_link_color": "0084B4",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": true,
            "default_profile": true,
            "default_profile_image": false,
            "following": null,
            "follow_request_sent": null,
            "notifications": null
        },
        "geo": null,
        "coordinates": null,
        "place": null,
        "contributors": null,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": false,
        "retweeted": false,
        "possibly_sensitive": false,
        "lang": "en"
    },
    {
        "created_at": "Fri Jun 07 10:00:02 +0000 2013",
        "id": 342944025831165950,
        "id_str": "342944025831165952",
        "text": "Lorem ipsum tweets at coffee time http://t.co/RfAeb8d9dh for web designers and wireframes 11:00 07-06-2013 #tweepsum",
        "source": "<a href=\"http://www.danfast.com\" rel=\"nofollow\">Tweepsum</a>",
        "truncated": false,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "in_reply_to_screen_name": null,
        "user": {
            "id": 242486125,
            "id_str": "242486125",
            "name": "Tweepsum",
            "screen_name": "tweepsum",
            "location": "Poole, Dorset, UK",
            "url": "http://danfast.com/tweepsum",
            "description": "Average & full length lorem ipsum tweets at coffee time each day for web designers or anyone needing a test Twitter feed",
            "protected": false,
            "followers_count": 59,
            "friends_count": 0,
            "listed_count": 0,
            "created_at": "Mon Jan 24 22:12:50 +0000 2011",
            "favourites_count": 0,
            "utc_offset": 0,
            "time_zone": "London",
            "geo_enabled": false,
            "verified": false,
            "statuses_count": 409,
            "lang": "en",
            "contributors_enabled": false,
            "is_translator": false,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_tile": false,
            "profile_image_url": "http://a0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_link_color": "0084B4",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": true,
            "default_profile": true,
            "default_profile_image": false,
            "following": null,
            "follow_request_sent": null,
            "notifications": null
        },
        "geo": null,
        "coordinates": null,
        "place": null,
        "contributors": null,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": false,
        "retweeted": false,
        "possibly_sensitive": false,
        "lang": "en"
    },
    {
        "created_at": "Thu Jun 06 10:00:02 +0000 2013",
        "id": 342581641706885100,
        "id_str": "342581641706885120",
        "text": "Lorem ipsum tweets followed by http://t.co/aIQiLM0h3P you should follow @tweepsum too 11:00 06-06-2013 #tweepsum",
        "source": "<a href=\"http://www.danfast.com\" rel=\"nofollow\">Tweepsum</a>",
        "truncated": false,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "in_reply_to_screen_name": null,
        "user": {
            "id": 242486125,
            "id_str": "242486125",
            "name": "Tweepsum",
            "screen_name": "tweepsum",
            "location": "Poole, Dorset, UK",
            "url": "http://danfast.com/tweepsum",
            "description": "Average & full length lorem ipsum tweets at coffee time each day for web designers or anyone needing a test Twitter feed",
            "protected": false,
            "followers_count": 59,
            "friends_count": 0,
            "listed_count": 0,
            "created_at": "Mon Jan 24 22:12:50 +0000 2011",
            "favourites_count": 0,
            "utc_offset": 0,
            "time_zone": "London",
            "geo_enabled": false,
            "verified": false,
            "statuses_count": 409,
            "lang": "en",
            "contributors_enabled": false,
            "is_translator": false,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_tile": false,
            "profile_image_url": "http://a0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_link_color": "0084B4",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": true,
            "default_profile": true,
            "default_profile_image": false,
            "following": null,
            "follow_request_sent": null,
            "notifications": null
        },
        "geo": null,
        "coordinates": null,
        "place": null,
        "contributors": null,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": false,
        "retweeted": false,
        "possibly_sensitive": false,
        "lang": "en"
    },
    {
        "created_at": "Wed Jun 05 10:00:03 +0000 2013",
        "id": 342219254780813300,
        "id_str": "342219254780813312",
        "text": "A lorem ipsum tweet at coffee time each day for web designers or anyone needing a test twitter feed 11:00 05-06-2013 #tweepsum",
        "source": "<a href=\"http://www.danfast.com\" rel=\"nofollow\">Tweepsum</a>",
        "truncated": false,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "in_reply_to_screen_name": null,
        "user": {
            "id": 242486125,
            "id_str": "242486125",
            "name": "Tweepsum",
            "screen_name": "tweepsum",
            "location": "Poole, Dorset, UK",
            "url": "http://danfast.com/tweepsum",
            "description": "Average & full length lorem ipsum tweets at coffee time each day for web designers or anyone needing a test Twitter feed",
            "protected": false,
            "followers_count": 59,
            "friends_count": 0,
            "listed_count": 0,
            "created_at": "Mon Jan 24 22:12:50 +0000 2011",
            "favourites_count": 0,
            "utc_offset": 0,
            "time_zone": "London",
            "geo_enabled": false,
            "verified": false,
            "statuses_count": 409,
            "lang": "en",
            "contributors_enabled": false,
            "is_translator": false,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_tile": false,
            "profile_image_url": "http://a0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_link_color": "0084B4",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": true,
            "default_profile": true,
            "default_profile_image": false,
            "following": null,
            "follow_request_sent": null,
            "notifications": null
        },
        "geo": null,
        "coordinates": null,
        "place": null,
        "contributors": null,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": false,
        "retweeted": false,
        "lang": "en"
    },
    {
        "created_at": "Tue Jun 04 10:00:01 +0000 2013",
        "id": 341856859042492400,
        "id_str": "341856859042492417",
        "text": "A lorem ipsum tweet at coffee time each day for web designers or anyone needing a test twitter feed 11:00 04-06-2013 #tweepsum",
        "source": "<a href=\"http://www.danfast.com\" rel=\"nofollow\">Tweepsum</a>",
        "truncated": false,
        "in_reply_to_status_id": null,
        "in_reply_to_status_id_str": null,
        "in_reply_to_user_id": null,
        "in_reply_to_user_id_str": null,
        "in_reply_to_screen_name": null,
        "user": {
            "id": 242486125,
            "id_str": "242486125",
            "name": "Tweepsum",
            "screen_name": "tweepsum",
            "location": "Poole, Dorset, UK",
            "url": "http://danfast.com/tweepsum",
            "description": "Average & full length lorem ipsum tweets at coffee time each day for web designers or anyone needing a test Twitter feed",
            "protected": false,
            "followers_count": 59,
            "friends_count": 0,
            "listed_count": 0,
            "created_at": "Mon Jan 24 22:12:50 +0000 2011",
            "favourites_count": 0,
            "utc_offset": 0,
            "time_zone": "London",
            "geo_enabled": false,
            "verified": false,
            "statuses_count": 409,
            "lang": "en",
            "contributors_enabled": false,
            "is_translator": false,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
            "profile_background_tile": false,
            "profile_image_url": "http://a0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_image_url_https": "https://si0.twimg.com/profile_images/1224856230/tweepsum_normal.jpg",
            "profile_link_color": "0084B4",
            "profile_sidebar_border_color": "C0DEED",
            "profile_sidebar_fill_color": "DDEEF6",
            "profile_text_color": "333333",
            "profile_use_background_image": true,
            "default_profile": true,
            "default_profile_image": false,
            "following": null,
            "follow_request_sent": null,
            "notifications": null
        },
        "geo": null,
        "coordinates": null,
        "place": null,
        "contributors": null,
        "retweet_count": 0,
        "favorite_count": 0,
        "favorited": false,
        "retweeted": false,
        "lang": "en"
    }
]